export const INDIAN_STOCKS = [
  // --- NIFTY 50 ---
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', sector: 'Energy', category: 'NIFTY 50' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', sector: 'Technology', category: 'NIFTY 50' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'INFY.NS', name: 'Infosys', sector: 'Technology', category: 'NIFTY 50' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', sector: 'Consumer Defensive', category: 'NIFTY 50' },
  { symbol: 'ITC.NS', name: 'ITC Limited', sector: 'Consumer Defensive', category: 'NIFTY 50' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', sector: 'Communication', category: 'NIFTY 50' },
  { symbol: 'LICI.NS', name: 'Life Insurance Corp', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro', sector: 'Industrials', category: 'NIFTY 50' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', sector: 'Technology', category: 'NIFTY 50' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki', sector: 'Consumer Cyclical', category: 'NIFTY 50' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical', sector: 'Healthcare', category: 'NIFTY 50' },
  { symbol: 'TITAN.NS', name: 'Titan Company', sector: 'Consumer Cyclical', category: 'NIFTY 50' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', sector: 'Consumer Cyclical', category: 'NIFTY 50' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement', sector: 'Basic Materials', category: 'NIFTY 50' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', sector: 'Consumer Cyclical', category: 'NIFTY 50' },
  { symbol: 'NTPC.NS', name: 'NTPC Limited', sector: 'Utilities', category: 'NIFTY 50' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corp', sector: 'Utilities', category: 'NIFTY 50' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', sector: 'Industrials', category: 'NIFTY 50' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports', sector: 'Industrials', category: 'NIFTY 50' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra', sector: 'Consumer Cyclical', category: 'NIFTY 50' },
  { symbol: 'ONGC.NS', name: 'ONGC', sector: 'Energy', category: 'NIFTY 50' },
  { symbol: 'COALINDIA.NS', name: 'Coal India', sector: 'Basic Materials', category: 'NIFTY 50' },
  { symbol: 'WIPRO.NS', name: 'Wipro', sector: 'Technology', category: 'NIFTY 50' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', sector: 'Basic Materials', category: 'NIFTY 50' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel', sector: 'Basic Materials', category: 'NIFTY 50' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', sector: 'Basic Materials', category: 'NIFTY 50' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', sector: 'Technology', category: 'NIFTY 50' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries', sector: 'Basic Materials', category: 'NIFTY 50' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India', sector: 'Consumer Defensive', category: 'NIFTY 50' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'DIVISLAB.NS', name: "Divi's Laboratories", sector: 'Healthcare', category: 'NIFTY 50' },
  { symbol: 'CIPLA.NS', name: 'Cipla', sector: 'Healthcare', category: 'NIFTY 50' },
  { symbol: 'DRREDDY.NS', name: "Dr. Reddy's Labs", sector: 'Healthcare', category: 'NIFTY 50' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries', sector: 'Consumer Defensive', category: 'NIFTY 50' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum', sector: 'Energy', category: 'NIFTY 50' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', sector: 'Consumer Cyclical', category: 'NIFTY 50' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp', sector: 'Consumer Cyclical', category: 'NIFTY 50' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', sector: 'Healthcare', category: 'NIFTY 50' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer', sector: 'Consumer Defensive', category: 'NIFTY 50' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance', sector: 'Financial', category: 'NIFTY 50' },
  { symbol: 'ADANIPOWER.NS', name: 'Adani Power', sector: 'Utilities', category: 'Nifty Next 50' },

  // --- NIFTY NEXT 50 ---
  { symbol: 'ZOMATO.NS', name: 'Zomato', sector: 'Technology', category: 'Nifty Next 50' },
  { symbol: 'HAL.NS', name: 'Hindustan Aeronautics', sector: 'Industrials', category: 'Nifty Next 50' },
  { symbol: 'JIOFIN.NS', name: 'Jio Financial', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'TRENT.NS', name: 'Trent Ltd', sector: 'Consumer Cyclical', category: 'Nifty Next 50' },
  { symbol: 'DLF.NS', name: 'DLF Limited', sector: 'Real Estate', category: 'Nifty Next 50' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics', sector: 'Industrials', category: 'Nifty Next 50' },
  { symbol: 'VBL.NS', name: 'Varun Beverages', sector: 'Consumer Defensive', category: 'Nifty Next 50' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Inv', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'SIEMENS.NS', name: 'Siemens India', sector: 'Industrials', category: 'Nifty Next 50' },
  { symbol: 'TVSMOTOR.NS', name: 'TVS Motor Company', sector: 'Consumer Cyclical', category: 'Nifty Next 50' },
  { symbol: 'HAVELLS.NS', name: 'Havells India', sector: 'Industrials', category: 'Nifty Next 50' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corp', sector: 'Energy', category: 'Nifty Next 50' },
  { symbol: 'VEDL.NS', name: 'Vedanta', sector: 'Basic Materials', category: 'Nifty Next 50' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer', sector: 'Consumer Defensive', category: 'Nifty Next 50' },
  { symbol: 'GAIL.NS', name: 'GAIL India', sector: 'Energy', category: 'Nifty Next 50' },
  { symbol: 'DABUR.NS', name: 'Dabur India', sector: 'Consumer Defensive', category: 'Nifty Next 50' },
  { symbol: 'ABB.NS', name: 'ABB India', sector: 'Industrials', category: 'Nifty Next 50' },
  { symbol: 'SHREECEM.NS', name: 'Shree Cement', sector: 'Basic Materials', category: 'Nifty Next 50' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements', sector: 'Basic Materials', category: 'Nifty Next 50' },
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation', sector: 'Industrials', category: 'Nifty Next 50' },
  { symbol: 'PNB.NS', name: 'Punjab National Bank', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'CANBK.NS', name: 'Canara Bank', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries', sector: 'Basic Materials', category: 'Nifty Next 50' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge', sector: 'Technology', category: 'Nifty Next 50' },
  { symbol: 'ICICIGI.NS', name: 'ICICI Lombard', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'SBICARD.NS', name: 'SBI Cards', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch Ltd', sector: 'Consumer Cyclical', category: 'Nifty Next 50' },
  { symbol: 'MARICO.NS', name: 'Marico', sector: 'Consumer Defensive', category: 'Nifty Next 50' },
  { symbol: 'COLPAL.NS', name: 'Colgate-Palmolive', sector: 'Consumer Defensive', category: 'Nifty Next 50' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints', sector: 'Basic Materials', category: 'Nifty Next 50' },
  { symbol: 'MOTHERSON.NS', name: 'Samvardhana Motherson', sector: 'Consumer Cyclical', category: 'Nifty Next 50' },
  { symbol: 'IRCTC.NS', name: 'IRCTC', sector: 'Consumer Cyclical', category: 'Nifty Next 50' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'PFC.NS', name: 'Power Finance Corp', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'RECLTD.NS', name: 'REC Limited', sector: 'Financial', category: 'Nifty Next 50' },
  { symbol: 'ADANIENSOL.NS', name: 'Adani Energy', sector: 'Utilities', category: 'Nifty Next 50' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green', sector: 'Utilities', category: 'Nifty Next 50' },
  { symbol: 'ATGL.NS', name: 'Adani Total Gas', sector: 'Utilities', category: 'Nifty Next 50' },
  { symbol: 'LODHA.NS', name: 'Macrotech Developers', sector: 'Real Estate', category: 'Nifty Next 50' },
  { symbol: 'SRF.NS', name: 'SRF Limited', sector: 'Basic Materials', category: 'Nifty Next 50' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', sector: 'Technology', category: 'Nifty Next 50' },
  { symbol: 'PIIND.NS', name: 'PI Industries', sector: 'Basic Materials', category: 'Nifty Next 50' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharma', sector: 'Healthcare', category: 'Nifty Next 50' },
  { symbol: 'ZYDUSLIFE.NS', name: 'Zydus Lifesciences', sector: 'Healthcare', category: 'Nifty Next 50' },
  { symbol: 'LUPIN.NS', name: 'Lupin', sector: 'Healthcare', category: 'Nifty Next 50' },
  { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma', sector: 'Healthcare', category: 'Nifty Next 50' },

  // --- NIFTY MIDCAP SELECT ---
  { symbol: 'POLYCAB.NS', name: 'Polycab India', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'FEDERALBNK.NS', name: 'Federal Bank', sector: 'Financial', category: 'Midcap' },
  { symbol: 'TATACOMM.NS', name: 'Tata Communications', sector: 'Communication', category: 'Midcap' },
  { symbol: 'ALKEM.NS', name: 'Alkem Labs', sector: 'Healthcare', category: 'Midcap' },
  { symbol: 'COFORGE.NS', name: 'Coforge', sector: 'Technology', category: 'Midcap' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems', sector: 'Technology', category: 'Midcap' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis', sector: 'Technology', category: 'Midcap' },
  { symbol: 'LTTS.NS', name: 'L&T Technology', sector: 'Technology', category: 'Midcap' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty', sector: 'Real Estate', category: 'Midcap' },
  { symbol: 'PHOENIXLTD.NS', name: 'Phoenix Mills', sector: 'Real Estate', category: 'Midcap' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates', sector: 'Real Estate', category: 'Midcap' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties', sector: 'Real Estate', category: 'Midcap' },
  { symbol: 'ASHOKLEY.NS', name: 'Ashok Leyland', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Ind', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'MRF.NS', name: 'MRF', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'BHARATFORG.NS', name: 'Bharat Forge', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'CUMMINSIND.NS', name: 'Cummins India', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'ASTRAL.NS', name: 'Astral', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'SUPREMEIND.NS', name: 'Supreme Ind', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'PAGEIND.NS', name: 'Page Industries', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'DEVYANI.NS', name: 'Devyani International', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'ABFRL.NS', name: 'Aditya Birla Fashion', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'BATAINDIA.NS', name: 'Bata India', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'UBL.NS', name: 'United Breweries', sector: 'Consumer Defensive', category: 'Midcap' },
  { symbol: 'MCDOWELL-N.NS', name: 'United Spirits', sector: 'Consumer Defensive', category: 'Midcap' },
  { symbol: 'RADICO.NS', name: 'Radico Khaitan', sector: 'Consumer Defensive', category: 'Midcap' },
  { symbol: 'VOLTAS.NS', name: 'Voltas', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'WHIRLPOOL.NS', name: 'Whirlpool India', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies', sector: 'Technology', category: 'Midcap' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Greaves', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics', sector: 'Industrials', category: 'Midcap' },
  { symbol: 'APLAPOLLO.NS', name: 'APL Apollo', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'JSWENERGY.NS', name: 'JSW Energy', sector: 'Utilities', category: 'Midcap' },
  { symbol: 'TORNTPOWER.NS', name: 'Torrent Power', sector: 'Utilities', category: 'Midcap' },
  { symbol: 'TATACHEM.NS', name: 'Tata Chemicals', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'AARTIIND.NS', name: 'Aarti Industries', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'ATUL.NS', name: 'Atul Ltd', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'COROMANDEL.NS', name: 'Coromandel Intl', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'UPL.NS', name: 'UPL', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'LALPATHLAB.NS', name: "Dr. Lal PathLabs", sector: 'Healthcare', category: 'Midcap' },
  { symbol: 'METROBRAND.NS', name: 'Metro Brands', sector: 'Consumer Cyclical', category: 'Midcap' },
  { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra', sector: 'Financial', category: 'Midcap' },
  { symbol: 'IDBI.NS', name: 'IDBI Bank', sector: 'Financial', category: 'Midcap' },
  { symbol: 'YESBANK.NS', name: 'Yes Bank', sector: 'Financial', category: 'Midcap' },
  { symbol: 'ABCAPITAL.NS', name: 'Aditya Birla Capital', sector: 'Financial', category: 'Midcap' },
  { symbol: 'MFSL.NS', name: 'Max Financial', sector: 'Financial', category: 'Midcap' },
  { symbol: 'POONAWALLA.NS', name: 'Poonawalla Fincorp', sector: 'Financial', category: 'Midcap' },
  { symbol: 'SUNDARMFIN.NS', name: 'Sundaram Finance', sector: 'Financial', category: 'Midcap' },
  { symbol: 'BANDHANBNK.NS', name: 'Bandhan Bank', sector: 'Financial', category: 'Midcap' },
  { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank', sector: 'Financial', category: 'Midcap' },
  { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'SAIL.NS', name: 'SAIL', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'DALBHARAT.NS', name: 'Dalmia Bharat', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'ACC.NS', name: 'ACC', sector: 'Basic Materials', category: 'Midcap' },
  { symbol: 'JKCEMENT.NS', name: 'JK Cement', sector: 'Basic Materials', category: 'Midcap' },

  // --- NIFTY SMALLCAP SELECT ---
  { symbol: 'BSE.NS', name: 'BSE Limited', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'CDSL.NS', name: 'CDSL', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'MCX.NS', name: 'MCX India', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'IEX.NS', name: 'Indian Energy Exchange', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'ANGELONE.NS', name: 'Angel One', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'SUZLON.NS', name: 'Suzlon Energy', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'KALYANKJIL.NS', name: 'Kalyan Jewellers', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'IRFC.NS', name: 'Indian Railway Finance', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'IRCON.NS', name: 'Ircon International', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'RITES.NS', name: 'RITES', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'HUDCO.NS', name: 'HUDCO', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'NBCC.NS', name: 'NBCC India', sector: 'Real Estate', category: 'Smallcap' },
  { symbol: 'NCC.NS', name: 'NCC Limited', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'SJVN.NS', name: 'SJVN', sector: 'Utilities', category: 'Smallcap' },
  { symbol: 'NHPC.NS', name: 'NHPC', sector: 'Utilities', category: 'Smallcap' },
  { symbol: 'NLCINDIA.NS', name: 'NLC India', sector: 'Utilities', category: 'Smallcap' },
  { symbol: 'KEI.NS', name: 'KEI Industries', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'KEC.NS', name: 'KEC International', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'CYIENT.NS', name: 'Cyient', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'ZENSARTECH.NS', name: 'Zensar Technologies', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'SONACOMS.NS', name: 'Sona BLW Precision', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'JBCHEPHARM.NS', name: "J.B. Chemicals", sector: 'Healthcare', category: 'Smallcap' },
  { symbol: 'GLENMARK.NS', name: 'Glenmark Pharma', sector: 'Healthcare', category: 'Smallcap' },
  { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma', sector: 'Healthcare', category: 'Smallcap' },
  { symbol: 'GRANULES.NS', name: 'Granules India', sector: 'Healthcare', category: 'Smallcap' },
  { symbol: 'BIOCON.NS', name: 'Biocon', sector: 'Healthcare', category: 'Smallcap' },
  { symbol: 'LAURUSLABS.NS', name: 'Laurus Labs', sector: 'Healthcare', category: 'Smallcap' },
  { symbol: 'PVRINOX.NS', name: 'PVR INOX', sector: 'Communication', category: 'Smallcap' },
  { symbol: 'EASEMYTRIP.NS', name: 'Easy Trip Planners', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'DELHIVERY.NS', name: 'Delhivery', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'BLUEDART.NS', name: 'Blue Dart', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'CENTURYPLY.NS', name: 'Century Plyboards', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'CERA.NS', name: 'Cera Sanitaryware', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'AMBER.NS', name: 'Amber Enterprises', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'VIPIND.NS', name: 'VIP Industries', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'TTML.NS', name: 'Tata Teleservices', sector: 'Communication', category: 'Smallcap' },
  { symbol: 'TEJASNET.NS', name: 'Tejas Networks', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'HFCL.NS', name: 'HFCL', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'ITI.NS', name: 'ITI Limited', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'GSFC.NS', name: 'GSFC', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'GNFC.NS', name: 'GNFC', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'CHAMBLFERT.NS', name: 'Chambal Fertilisers', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'FACT.NS', name: 'FACT', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'NATIONALUM.NS', name: 'National Aluminium', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'HINDCOPPER.NS', name: 'Hindustan Copper', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'GMDC.NS', name: 'GMDC', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'MOIL.NS', name: 'MOIL', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'APARINDS.NS', name: 'Apar Industries', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'ELGIEQUIP.NS', name: 'Elgi Equipments', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'TRITURBINE.NS', name: 'Triveni Turbine', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'GRINDWELL.NS', name: 'Grindwell Norton', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'SCHAEFFLER.NS', name: 'Schaeffler India', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'SKFINDIA.NS', name: 'SKF India', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'TIMKEN.NS', name: 'Timken India', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'AIAENG.NS', name: 'AIA Engineering', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises', sector: 'Real Estate', category: 'Smallcap' },
  { symbol: 'SOBHA.NS', name: 'Sobha', sector: 'Real Estate', category: 'Smallcap' },
  { symbol: 'MAHLIFE.NS', name: 'Mahindra Lifespace', sector: 'Real Estate', category: 'Smallcap' },
  { symbol: 'RAYMOND.NS', name: 'Raymond', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'TRIDENT.NS', name: 'Trident', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'WELSPUNLIV.NS', name: 'Welspun Living', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'VGUARD.NS', name: 'V-Guard', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'SYMPHONY.NS', name: 'Symphony', sector: 'Consumer Cyclical', category: 'Smallcap' },
  { symbol: 'BLUESTARCO.NS', name: 'Blue Star', sector: 'Industrials', category: 'Smallcap' },
  { symbol: 'INTELLECT.NS', name: 'Intellect Design', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'TANLA.NS', name: 'Tanla Platforms', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'ROUTE.NS', name: 'Route Mobile', sector: 'Technology', category: 'Smallcap' },
  { symbol: 'BIRLACORPN.NS', name: 'Birla Corp', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'STARCEMENT.NS', name: 'Star Cement', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'JKLAKSHMI.NS', name: 'JK Lakshmi Cement', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'CENTURYTEX.NS', name: 'Century Textiles', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'AEGISCHEM.NS', name: 'Aegis Logistics', sector: 'Energy', category: 'Smallcap' },
  { symbol: 'MRPL.NS', name: 'MRPL', sector: 'Energy', category: 'Smallcap' },
  { symbol: 'CHENNPETRO.NS', name: 'Chennai Petroleum', sector: 'Energy', category: 'Smallcap' },
  { symbol: 'CASTROLIND.NS', name: 'Castrol India', sector: 'Basic Materials', category: 'Smallcap' },
  { symbol: 'OIL.NS', name: 'Oil India', sector: 'Energy', category: 'Smallcap' },
  { symbol: 'GSPL.NS', name: 'GSPL', sector: 'Utilities', category: 'Smallcap' },
  { symbol: 'MGL.NS', name: 'Mahanagar Gas', sector: 'Utilities', category: 'Smallcap' },
  { symbol: 'IGL.NS', name: 'Indraprastha Gas', sector: 'Utilities', category: 'Smallcap' },
  { symbol: 'GUJGASLTD.NS', name: 'Gujarat Gas', sector: 'Utilities', category: 'Smallcap' },
  { symbol: 'KA-NS', name: 'Karnataka Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'CUB.NS', name: 'City Union Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'KARURVYSYA.NS', name: 'Karur Vysya Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'RBLBANK.NS', name: 'RBL Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'J&KBANK.NS', name: 'J&K Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'SOUTHBANK.NS', name: 'South Indian Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'UCOBANK.NS', name: 'UCO Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'IOB.NS', name: 'Indian Overseas Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'CENTRALBK.NS', name: 'Central Bank', sector: 'Financial', category: 'Smallcap' },
  { symbol: 'PSB.NS', name: 'Punjab & Sind Bank', sector: 'Financial', category: 'Smallcap' },
];

export const US_STOCKS = [
  // --- TECHNOLOGY ---
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology', category: 'US Large' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', sector: 'Technology', category: 'US Large' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', sector: 'Technology', category: 'US Large' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology', category: 'US Large' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Technology', category: 'US Large' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology', category: 'US Large' },
  { symbol: 'ORCL', name: 'Oracle Corp.', sector: 'Technology', category: 'US Large' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology', category: 'US Large' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology', category: 'US Large' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Technology', category: 'US Large' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Communication', category: 'US Large' },
  { symbol: 'INTC', name: 'Intel Corp', sector: 'Technology', category: 'US Large' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology', category: 'US Large' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology', category: 'US Large' },
  { symbol: 'IBM', name: 'IBM', sector: 'Technology', category: 'US Large' },
  { symbol: 'CSCO', name: 'Cisco Systems', sector: 'Technology', category: 'US Large' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Technology', category: 'US Large' },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Technology', category: 'US Large' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology', category: 'US Large' },
  { symbol: 'SNOW', name: 'Snowflake', sector: 'Technology', category: 'US Large' },
  { symbol: 'PLTR', name: 'Palantir', sector: 'Technology', category: 'US Large' },
  { symbol: 'SQ', name: 'Block Inc.', sector: 'Technology', category: 'US Large' },
  { symbol: 'SHOP', name: 'Shopify', sector: 'Technology', category: 'US Large' },
  
  // --- FINANCIAL ---
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Financial', category: 'US Large' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financial', category: 'US Large' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Financial', category: 'US Large' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Financial', category: 'US Large' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Financial', category: 'US Large' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financial', category: 'US Large' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financial', category: 'US Large' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Financial', category: 'US Large' },
  { symbol: 'C', name: 'Citigroup', sector: 'Financial', category: 'US Large' },
  { symbol: 'AXP', name: 'American Express', sector: 'Financial', category: 'US Large' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Financial', category: 'US Large' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Financial', category: 'US Large' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', sector: 'Financial', category: 'US Large' },
  
  // --- HEALTHCARE ---
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'MRK', name: 'Merck & Co.', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'ABT', name: 'Abbott Labs', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'DHR', name: 'Danaher', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare', category: 'US Large' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare', category: 'US Large' },
  
  // --- CONSUMER ---
  { symbol: 'WMT', name: 'Walmart', sector: 'Consumer Defensive', category: 'US Large' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer Defensive', category: 'US Large' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Consumer Defensive', category: 'US Large' },
  { symbol: 'COST', name: 'Costco', sector: 'Consumer Defensive', category: 'US Large' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer Defensive', category: 'US Large' },
  { symbol: 'MCD', name: "McDonald's", sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'DIS', name: 'Walt Disney', sector: 'Communication', category: 'US Large' },
  { symbol: 'TGT', name: 'Target', sector: 'Consumer Defensive', category: 'US Large' },
  { symbol: 'LOW', name: "Lowe's", sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Consumer Cyclical', category: 'US Large' },
  
  // --- ENERGY / INDUSTRIAL ---
  { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy', category: 'US Large' },
  { symbol: 'CVX', name: 'Chevron', sector: 'Energy', category: 'US Large' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrials', category: 'US Large' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrials', category: 'US Large' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrials', category: 'US Large' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrials', category: 'US Large' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrials', category: 'US Large' },
  { symbol: 'UPS', name: 'UPS', sector: 'Industrials', category: 'US Large' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials', category: 'US Large' },
  { symbol: 'DE', name: 'Deere & Co', sector: 'Industrials', category: 'US Large' },
  { symbol: 'RTX', name: 'Raytheon', sector: 'Industrials', category: 'US Large' },
  { symbol: 'MMM', name: '3M', sector: 'Industrials', category: 'US Large' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy', category: 'US Large' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy', category: 'US Large' },
  
  // --- COMMUNICATION ---
  { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Communication', category: 'US Large' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Communication', category: 'US Large' },
  { symbol: 'T', name: 'AT&T', sector: 'Communication', category: 'US Large' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Communication', category: 'US Large' },
  
  // --- REAL ESTATE / UTILITIES ---
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate', category: 'US Large' },
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate', category: 'US Large' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities', category: 'US Large' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities', category: 'US Large' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities', category: 'US Large' },
  
  // --- ADDITIONAL TECH / GROWTH ---
  { symbol: 'ARM', name: 'Arm Holdings', sector: 'Technology', category: 'US Large' },
  { symbol: 'MU', name: 'Micron', sector: 'Technology', category: 'US Large' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology', category: 'US Large' },
  { symbol: 'KLAC', name: 'KLA Corp', sector: 'Technology', category: 'US Large' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology', category: 'US Large' },
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Technology', category: 'US Large' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology', category: 'US Large' },
  { symbol: 'MRVL', name: 'Marvell Tech', sector: 'Technology', category: 'US Large' },
  { symbol: 'MSTR', name: 'MicroStrategy', sector: 'Technology', category: 'US Large' },
  { symbol: 'RBLX', name: 'Roblox', sector: 'Technology', category: 'US Large' },
  { symbol: 'U', name: 'Unity Software', sector: 'Technology', category: 'US Large' },
  { symbol: 'HOOD', name: 'Robinhood', sector: 'Financial', category: 'US Large' },
  { symbol: 'DKNG', name: 'DraftKings', sector: 'Consumer Cyclical', category: 'US Large' },
  { symbol: 'DASH', name: 'DoorDash', sector: 'Technology', category: 'US Large' },
  { symbol: 'NET', name: 'Cloudflare', sector: 'Technology', category: 'US Large' },
  { symbol: 'ZS', name: 'Zscaler', sector: 'Technology', category: 'US Large' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology', category: 'US Large' },
  { symbol: 'DDOG', name: 'Datadog', sector: 'Technology', category: 'US Large' },
  { symbol: 'TTD', name: 'The Trade Desk', sector: 'Technology', category: 'US Large' },
  { symbol: 'MDB', name: 'MongoDB', sector: 'Technology', category: 'US Large' },
  { symbol: 'TEAM', name: 'Atlassian', sector: 'Technology', category: 'US Large' },
  { symbol: 'HUBS', name: 'HubSpot', sector: 'Technology', category: 'US Large' },
  { symbol: 'OKTA', name: 'Okta', sector: 'Technology', category: 'US Large' },
  { symbol: 'TWLO', name: 'Twilio', sector: 'Technology', category: 'US Large' },
  { symbol: 'DOCU', name: 'DocuSign', sector: 'Technology', category: 'US Large' },
  { symbol: 'PATH', name: 'UiPath', sector: 'Technology', category: 'US Large' },
  { symbol: 'GTLB', name: 'GitLab', sector: 'Technology', category: 'US Large' },
  { symbol: 'HCP', name: 'HashiCorp', sector: 'Technology', category: 'US Large' },
  { symbol: 'CFLT', name: 'Confluent', sector: 'Technology', category: 'US Large' },
  { symbol: 'IOT', name: 'Samsara', sector: 'Technology', category: 'US Large' },
  { symbol: 'AI', name: 'C3.ai', sector: 'Technology', category: 'US Large' },
  { symbol: 'IONQ', name: 'IonQ', sector: 'Technology', category: 'US Large' },
  { symbol: 'RGTI', name: 'Rigetti Computing', sector: 'Technology', category: 'US Large' },
  { symbol: 'QUBT', name: 'Quantum Computing', sector: 'Technology', category: 'US Large' },
  { symbol: 'WOLF', name: 'Wolfspeed', sector: 'Technology', category: 'US Large' },
  { symbol: 'ON', name: 'ON Semiconductor', sector: 'Technology', category: 'US Large' },
  { symbol: 'STM', name: 'STMicroelectronics', sector: 'Technology', category: 'US Large' },
  { symbol: 'MCHP', name: 'Microchip Tech', sector: 'Technology', category: 'US Large' },
  { symbol: 'SWKS', name: 'Skyworks', sector: 'Technology', category: 'US Large' },
  { symbol: 'QRVO', name: 'Qorvo', sector: 'Technology', category: 'US Large' },
  { symbol: 'TER', name: 'Teradyne', sector: 'Technology', category: 'US Large' },
  { symbol: 'ENTG', name: 'Entegris', sector: 'Technology', category: 'US Large' },
  { symbol: 'MPWR', name: 'Monolithic Power', sector: 'Technology', category: 'US Large' },
  { symbol: 'LSCC', name: 'Lattice Semi', sector: 'Technology', category: 'US Large' },
  { symbol: 'RMBS', name: 'Rambus', sector: 'Technology', category: 'US Large' },
  { symbol: 'DIOD', name: 'Diodes Inc', sector: 'Technology', category: 'US Large' },
  { symbol: 'SLAB', name: 'Silicon Labs', sector: 'Technology', category: 'US Large' },
  { symbol: 'SMTC', name: 'Semtech', sector: 'Technology', category: 'US Large' },
  { symbol: 'POWI', name: 'Power Integrations', sector: 'Technology', category: 'US Large' },
  { symbol: 'CRUS', name: 'Cirrus Logic', sector: 'Technology', category: 'US Large' },
  { symbol: 'MTSI', name: 'MACOM', sector: 'Technology', category: 'US Large' },
  { symbol: 'MXL', name: 'MaxLinear', sector: 'Technology', category: 'US Large' },
  { symbol: 'AOS', name: 'Alpha and Omega', sector: 'Technology', category: 'US Large' },
  { symbol: 'VECO', name: 'Veeco', sector: 'Technology', category: 'US Large' },
  { symbol: 'ACLS', name: 'Axcelis', sector: 'Technology', category: 'US Large' },
  { symbol: 'COHR', name: 'Coherent', sector: 'Technology', category: 'US Large' },
  { symbol: 'LITE', name: 'Lumentum', sector: 'Technology', category: 'US Large' },
  { symbol: 'IPGP', name: 'IPG Photonics', sector: 'Technology', category: 'US Large' },
  { symbol: 'MKSI', name: 'MKS Instruments', sector: 'Technology', category: 'US Large' },
  { symbol: 'NOV', name: 'NOV Inc', sector: 'Energy', category: 'US Large' },
  { symbol: 'HAL', name: 'Halliburton', sector: 'Energy', category: 'US Large' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy', category: 'US Large' },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy', category: 'US Large' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy', category: 'US Large' },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy', category: 'US Large' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy', category: 'US Large' },
  { symbol: 'PXD', name: 'Pioneer Natural', sector: 'Energy', category: 'US Large' },
  { symbol: 'OXY', name: 'Occidental', sector: 'Energy', category: 'US Large' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy', category: 'US Large' },
  { symbol: 'HES', name: 'Hess Corp', sector: 'Energy', category: 'US Large' },
  { symbol: 'FANG', name: 'Diamondback', sector: 'Energy', category: 'US Large' },
  { symbol: 'CTRA', name: 'Coterra', sector: 'Energy', category: 'US Large' },
  { symbol: 'MRO', name: 'Marathon Oil', sector: 'Energy', category: 'US Large' },
  { symbol: 'APA', name: 'APA Corp', sector: 'Energy', category: 'US Large' },
  { symbol: 'EQT', name: 'EQT Corp', category: 'US Large' },
  { symbol: 'OVV', name: 'Ovintiv', sector: 'Energy', category: 'US Large' },
  { symbol: 'CHK', name: 'Chesapeake', sector: 'Energy', category: 'US Large' },
  { symbol: 'SWN', name: 'Southwestern', sector: 'Energy', category: 'US Large' },
  { symbol: 'RRC', name: 'Range Resources', sector: 'Energy', category: 'US Large' },
  { symbol: 'AR', name: 'Antero Resources', sector: 'Energy', category: 'US Large' },
  { symbol: 'MTDR', name: 'Matador', sector: 'Energy', category: 'US Large' },
  { symbol: 'PDCE', name: 'PDC Energy', sector: 'Energy', category: 'US Large' },
  { symbol: 'MUR', name: 'Murphy Oil', sector: 'Energy', category: 'US Large' },
  { symbol: 'SM', name: 'SM Energy', sector: 'Energy', category: 'US Large' },
  { symbol: 'CPE', name: 'Callon', sector: 'Energy', category: 'US Large' },
  { symbol: 'MGY', name: 'Magnolia', sector: 'Energy', category: 'US Large' },
  { symbol: 'CIVI', name: 'Civitas', sector: 'Energy', category: 'US Large' },
  { symbol: 'ESTE', name: 'Earthstone', sector: 'Energy', category: 'US Large' },
  { symbol: 'VTLE', name: 'Vital Energy', sector: 'Energy', category: 'US Large' },
  { symbol: 'CRK', name: 'Comstock', sector: 'Energy', category: 'US Large' },
  { symbol: 'CNX', name: 'CNX Resources', sector: 'Energy', category: 'US Large' },
  { symbol: 'GPOR', name: 'Gulfport', sector: 'Energy', category: 'US Large' },
  { symbol: 'WLL', name: 'Whiting', sector: 'Energy', category: 'US Large' },
  { symbol: 'OAS', name: 'Oasis', sector: 'Energy', category: 'US Large' },
  { symbol: 'CDEV', name: 'Centennial', sector: 'Energy', category: 'US Large' },
  { symbol: 'LPI', name: 'Laredo', sector: 'Energy', category: 'US Large' },
  { symbol: 'TALO', name: 'Talos', sector: 'Energy', category: 'US Large' },
  { symbol: 'REPX', name: 'Riley', sector: 'Energy', category: 'US Large' },
  { symbol: 'SBOW', name: 'SilverBow', sector: 'Energy', category: 'US Large' },
  { symbol: 'ROCC', name: 'Ranger', sector: 'Energy', category: 'US Large' },
  { symbol: 'BATL', name: 'Battalion', sector: 'Energy', category: 'US Large' },
  { symbol: 'AMPY', name: 'Amplify', sector: 'Energy', category: 'US Large' },
  { symbol: 'BRY', name: 'Berry', sector: 'Energy', category: 'US Large' },
  { symbol: 'EGY', name: 'Vaalco', sector: 'Energy', category: 'US Large' },
  { symbol: 'KOS', name: 'Kosmos', sector: 'Energy', category: 'US Large' },
  { symbol: 'WTI', name: 'W&T Offshore', sector: 'Energy', category: 'US Large' },
];

const STORAGE_KEY = 'quantmind_user_stocks';

export const getUserStocks = (market: 'IND' | 'US') => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) return [];
    const allCustom = JSON.parse(stored);
    return allCustom.filter((s: any) => s.market === market);
  } catch { return []; }
};

export const addUserStockToStorage = (stock: any) => {
  const stored = localStorage.getItem(STORAGE_KEY);
  const current = stored ? JSON.parse(stored) : [];
  if (current.find((s: any) => s.symbol === stock.symbol)) return;
  current.push(stock);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(current));
};

export const getStocks = (market: 'IND' | 'US') => {
  const base = market === 'IND' ? INDIAN_STOCKS : US_STOCKS;
  const custom = getUserStocks(market);
  return [...custom, ...base];
};

export const STOCK_UNIVERSE = INDIAN_STOCKS;